language: rust
rust:
    #- stable
    #- beta
  - nightly

before_script:
  - rustup component add rustfmt-preview

script:
  - "[ '$TRAVIS_RUST_VERSION' != 'nightly' ] || cargo fmt --all -- --write-mode diff"
  - cargo build --all
  - cargo test --all -- --test-threads 1

cache: cargo
