[package]
name = "lpn"
version = "0.1.0"
authors = ["Thom Wiggers <thom@thomwiggers.nl>"]
license = 'MIT'

[dependencies]
rand = "^0.5.0"
fnv = "^1.0.6"
itertools = "^0.7.8"
rayon = "1.0.1"
lazy_static = "1"
binomial-iter = "0.1.0"
num-rational = "0.2"
num-bigint = "0.2"
num-traits = "0.2"
factorial = "0.1"
time = "0.1"
m4ri_rust = "0.1"

[features]
default = ['nodebug']
nodebug = []

[profile.release]
opt-level = 3
lto = true
debug-assertions = false
codegen-units = 1
overflow-checks = false
