[package]
name = "lpn"
version = "0.1.0"
authors = ["Thom Wiggers <thom@thomwiggers.nl>"]

[dependencies]
rand = "^0.4.2"
fnv = "^1.0.6"
itertools = "^0.7.8"

[dependencies.m4ri-rust]
git = "https://github.com/thomwiggers/m4ri-rust.git"
#features = ["system_alloc"]

[profile.release]
lto = true
