[package]
name = "lpn"
version = "0.1.0"
authors = ["Thom Wiggers <thom@thomwiggers.nl>"]

[dependencies]
rand = "^0.5.0"
fnv = "^1.0.6"
itertools = "^0.7.8"
rayon = "1.0.1"

[dependencies.m4ri-rust]
git = "https://github.com/thomwiggers/m4ri-rust.git"
features = ["strassen_mul"]
#features = ["system_alloc"]

[profile.release]
opt-level = 3
lto = true
debug-assertions = false
codegen-units = 1
overflow-checks = false
